#!/bin/sh

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"

for i in vim tmux; do
	cd $i && ./setup
	cd -
done

mkdir -p ~/.config/nvim
cp -r nvim ~/.config/nvim

if [ -d ~/.local/share/konsole ]; then
	cp onedark.colorscheme ~/.local/share/konsole
fi
